### ISSUE TITLE
pint.phar missing for latest release

### ISSUE THREAD

**Issue by Rene-Welbers** [laravel/pint#349]
### Pint Version

1.21.0

### PHP Version

8.4.4, 8.3

### Description

With the latest release there was no pint.phar included  https://github.com/laravel/pint/releases

that broke some dependant github actions, for e.g. using pint in the shivammathur/setup-php action, see my issue here and the response: https://github.com/shivammathur/setup-php/issues/920#issuecomment-2678219804

### Steps To Reproduce

use github action and try to install pint with it
```yaml
- name: setup-php
  uses: shivammathur/setup-php@v2
  with:
    php-version: 8.4
    tools: pint
```
