### ISSUE TITLE
cs2pr support?

### ISSUE THREAD

**Issue by ptrkcsk** [laravel/pint#61]
i like to use [cs2pr](https://github.com/staabm/annotate-pull-request-from-checkstyle#using-php-coding-standards-fixer) to get pr annotations for php-cs-fixer issues

here's a rough example github workflow :

```yaml
name: Lint

jobs:
  lint:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: cs2pr

      - name: Run PHP Coding Standards Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
```
